### ISSUE TITLE
Migration to different aws region

### ISSUE THREAD

**Issue by daniele-xp** [xpeppers/trackerbot#21]
Now lambda and dynamo db are deployed on `us-east-1` (North Virginia)

Move them into a cheaper aws region.

**Comment by ilbonte** [comment]
maybe @ddepaoli3 could help with this

**Comment by orione-team** [comment]
Migrato a eu-west
Per fare questo abbiamo fatto:
1) backup di DynamoDB e re-importato i dati sulla nuova region.
2) eliminato le policy associate al ruolo `trackerbot-executor` <small>[[1]](https://github.com/claudiajs/claudia/issues/9#issuecomment-281415771)</small>
3) eliminato il ruolo `trackerbot-executor` 
4) eliminato il file `claudia.json`
5) lanciato `claudia create` attraverso npm (si occupa lui di crare lamba e i vari ruoli e policy)
6) copiato l'url fornito da `claudia` sulla pagina di configurazione di slack del trackerbot
7) inserito il token presente sulla pagina di configurazione del trackerbot in `claudia` quando richiesto (2 volte lo stesso token)
8) eliminato la vecchia lambda
