### ISSUE TITLE
Day off

### ISSUE THREAD

**Issue by daniele-xp** [xpeppers/trackerbot#24]
`/t ferie 14` could track the 14 under project "Assenza" with tag "Ferie" (as standard procedure wants)

**Comment by ilbonte** [comment]
I can work on this in the next "pomodori di studio" :)

**Comment by daniele-xp** [comment]
@ilbonte if you want we can do it together in pair ;)

**Comment by ilbonte** [comment]
I'm working on the last two open points: https://github.com/ilbonte/trackerbot/commit/35583296559ccea59f8e64641167b926b2282052

The feature is available but the code should be refactored
